name: Criar e implantar localmente

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          # Verifique se o nome do secret no GitHub est치 EXATAMENTE assim
          username: ${{ secrets.DOKERHUB_USER }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e push da imagem
        run: |
          docker build -t elivandrolopes/portaria:7.0 .
          docker push elivandrolopes/portaria:7.0

  deploy:
    needs: build
    runs-on: [self-hosted, Linux]
    steps:
      - name: Deploy local com Docker Compose
        run: |
          # Caminho absoluto para o diret칩rio onde est치 o seu docker-compose.yml
          cd /media/grupomateus/3f9a2e1e-ae3c-4ea5-9750-035aa9017e4d/servidor
          docker compose pull portaria-app
          docker compose up -d portaria-app
